// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func MintExtensionsShowPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = backButtonAndTextDirection(
			[]DirectionParams{
				{Direction: "Dashboard"},
				{Direction: "Mint Extensions"},
			}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = extensionWithSwitchExtensionButton("Mint", "").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p class=\"font-normal text-3xl text-left mt-[3.938rem]\">Here are the various extension on the Mint account</p><p class=\"text-[#A3A3A3] font-normal text-sm text-left tracking-[0.0025em]\">Note, some extension are dependent on another, so if such extension is used, you automatically use its dependent</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = availableExtensions(
			[]availableExtenisonsParam{
				{ExtensionName: "Metadata & Metadata pointer Extension"},
				{ExtensionName: "Non-Transfer Token Extension"},
				{ExtensionName: "Transfer Fee Extension"},
				{ExtensionName: "MintClose Authority Extension"},
				{ExtensionName: "Group & Group pointer Extension"},
				{ExtensionName: "Member & Member pointer Extension"},
				{ExtensionName: "Interest Bearing Token Extension"},
				{ExtensionName: "Permanent Delegate Extension"},
				{ExtensionName: "Transfer Hook Extension"},
				{ExtensionName: "Default Account State Extension"},
			}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = addExtensionButton("mint", "").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
